language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.8"
arch:
  - arm64
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz
before_install:
  - wget -q "https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh" -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -u -b -p $HOME/miniconda3
  - export PATH=$HOME/miniconda3/bin:$PATH
  - ~/miniconda3/bin/conda install conda-build -y
  - ~/miniconda3/bin/conda create -q -y --name testenv python=3.8 cython numpy pytest psutil pip
  - source ~/miniconda3/bin/activate testenv
  - pip install -U pip setuptools wheel
install:
  - pip install -r requirements.txt
  - pip install -e .[all]
  - mkdir -p ~/scikit_learn_data/mldata
  - wget -P ~/scikit_learn_data/mldata https://github.com/amplab/datascience-sp14/raw/master/lab7/mldata/mnist-original.mat
script: py.test
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
